 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/confirmations", type: :request do
  # Confirmation. As you add validations to Confirmation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Confirmation.create! valid_attributes
      get confirmations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      confirmation = Confirmation.create! valid_attributes
      get confirmation_url(confirmation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_confirmation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      confirmation = Confirmation.create! valid_attributes
      get edit_confirmation_url(confirmation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Confirmation" do
        expect {
          post confirmations_url, params: { confirmation: valid_attributes }
        }.to change(Confirmation, :count).by(1)
      end

      it "redirects to the created confirmation" do
        post confirmations_url, params: { confirmation: valid_attributes }
        expect(response).to redirect_to(confirmation_url(Confirmation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Confirmation" do
        expect {
          post confirmations_url, params: { confirmation: invalid_attributes }
        }.to change(Confirmation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post confirmations_url, params: { confirmation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested confirmation" do
        confirmation = Confirmation.create! valid_attributes
        patch confirmation_url(confirmation), params: { confirmation: new_attributes }
        confirmation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the confirmation" do
        confirmation = Confirmation.create! valid_attributes
        patch confirmation_url(confirmation), params: { confirmation: new_attributes }
        confirmation.reload
        expect(response).to redirect_to(confirmation_url(confirmation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        confirmation = Confirmation.create! valid_attributes
        patch confirmation_url(confirmation), params: { confirmation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested confirmation" do
      confirmation = Confirmation.create! valid_attributes
      expect {
        delete confirmation_url(confirmation)
      }.to change(Confirmation, :count).by(-1)
    end

    it "redirects to the confirmations list" do
      confirmation = Confirmation.create! valid_attributes
      delete confirmation_url(confirmation)
      expect(response).to redirect_to(confirmations_url)
    end
  end
end
